# Stage 1
# FROM node:8.11.2-alpine as node
# FROM node:latest as node
FROM node:16.13.0 as node
# RUN apk update && apk add --no-cache make git
RUN npm install -g yarn  --force
WORKDIR /app
COPY ./ /app/
COPY package*.json ./
RUN yarn 
RUN yarn build 

# MULTI STAGE
FROM nginx:alpine
COPY --from=node /app/dist/client /usr/share/nginx/html
COPY ./nginx-custom.conf /etc/nginx/conf.d/default.conf